"""
Netflix Wrapped AI — Export Utilities
JSON, CSV, and text export helpers.
"""

import json
import pandas as pd
from typing import Dict, Any


def export_feature_vector_json(fv: Dict) -> str:
    """Return pretty-printed JSON of the feature vector."""
    return json.dumps(fv, indent=2, default=str)


def export_summary_text(metrics: Dict, narrative: Dict, archetype: Dict) -> str:
    """Generate a plain-text readable summary report."""
    lines = [
        "═" * 60,
        "  NETFLIX WRAPPED AI — BEHAVIORAL INTELLIGENCE REPORT",
        "═" * 60,
        "",
        f"  TOTAL HOURS STREAMED:  {metrics.get('total_hours', 0):,}",
        f"  UNIQUE TITLES:         {metrics.get('total_titles', 0):,}",
        f"  ACTIVE DAYS:           {metrics.get('days_active', 0)}",
        f"  LONGEST STREAK:        {metrics.get('longest_streak', 0)} days",
        f"  PEAK HOUR:             {metrics.get('peak_hour_label', '—')}",
        f"  PEAK DAY:              {metrics.get('peak_weekday', '—')}",
        "",
        "─" * 60,
        "  BEHAVIORAL KPIs",
        "─" * 60,
        f"  Binge Quotient:        {metrics.get('binge_quotient', 0)}/100",
        f"  Weekend Dominance:     {metrics.get('weekend_dominance', 0)}%",
        f"  Night Owl Index:       {metrics.get('night_owl_index', 0)}%",
        f"  Series Loyalty:        {metrics.get('series_loyalty', 0)}%",
        f"  Consistency Score:     {metrics.get('consistency_score', 0)}/100",
        f"  Content Diversity:     {metrics.get('content_diversity_pct', 0):.1f}%",
        f"  Recency Score:         {metrics.get('recency_score', 0)}/100",
        "",
        "─" * 60,
        "  STREAMING ARCHETYPE",
        "─" * 60,
        f"  {archetype.get('name', '—')}",
        f"  Traits: {', '.join(archetype.get('traits', []))}",
        "",
        "─" * 60,
        "  AI NARRATIVE",
        "─" * 60,
        narrative.get('opening', ''),
        "",
        narrative.get('stats', ''),
        "",
        narrative.get('binge', ''),
        "",
        narrative.get('closing', ''),
        "",
        "═" * 60,
        "  Generated by Netflix Wrapped AI — Behavioral Intelligence Platform",
        "═" * 60,
    ]
    return "\n".join(lines)


def dataframe_to_csv_bytes(df: pd.DataFrame) -> bytes:
    return df.to_csv(index=False).encode('utf-8')
